name: Monitor BORME Besos

on:
  schedule:
    # Se ejecuta de lunes a viernes a las 08:00 AM UTC (09:00 AM hora española)
    - cron: '0 8 * * 1-5'
  workflow_dispatch: # Permite probarlo manualmente cuando quieras

jobs:
  ejecutar-script:
    runs-runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar librerias
        run: pip install requests

      - name: Ejecutar rastreador
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python borme.py
